spring:
  application:
    name: deanery
  datasource:
    url: jdbc:postgresql://localhost:5432/deanery
    username: postgres
    password: 7218804
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  profiles:
    active: test

logging:
  level:
    tech.inno.demodeanery: debug