spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: deanery
  datasource:
    url: jdbc:postgresql://localhost:5432/deanery
    username: postgres
    password: 7218804
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  profiles:
    active: test

app:
  kafka:
    kafkaMessageTopic: "message-topic"
    kafkaMessageGroupId: "kafka-message-group-id"

logging:
  level:
    tech.inno.demodeanery: debug